# Generated by Django 4.1.6 on 2023-03-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='otv_pod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otv_pod', models.CharField(blank=True, default='Не определено', max_length=50, null=True, verbose_name='Ответственное подразделение')),
            ],
        ),
    ]
