# Generated by Django 4.1.6 on 2023-03-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0002_otv_pod'),
    ]

    operations = [
        migrations.CreateModel(
            name='prichina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prichina', models.CharField(blank=True, default='Не определена', max_length=50, null=True, verbose_name='Причина')),
            ],
        ),
        migrations.CreateModel(
            name='uchastok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uchastok', models.CharField(blank=True, default='Не определено', max_length=50, null=True, verbose_name='Где произошол простой')),
            ],
        ),
    ]
