# Generated by Django 4.1.6 on 2023-03-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0004_prichina_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table5',
            options={'verbose_name_plural': 'Простои 5 линии'},
        ),
    ]
