# Generated by Django 4.1.6 on 2023-03-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0007_bottleexplosion_alter_table5_otv_pod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottleexplosion',
            name='bottle',
            field=models.IntegerField(verbose_name='Взрыв'),
        ),
    ]
