# Generated by Django 4.1.6 on 2023-04-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0009_bottling_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table5',
            name='comment',
            field=models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Комментарий'),
        ),
    ]
