# Generated by Django 4.1.6 on 2023-04-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0010_alter_table5_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='speed2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('speed', models.IntegerField(verbose_name='Скорость линии')),
            ],
            options={
                'verbose_name_plural': 'Производительность линии 2',
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdata', models.DateField(verbose_name='Дата начала простоя')),
                ('starttime', models.TimeField(verbose_name='Время начала простоя')),
                ('prostoy', models.TimeField(blank=True, null=True, verbose_name='Время простоя')),
                ('uchastok', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Где произошол простой')),
                ('prichina', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Причина')),
                ('otv_pod', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ответственное подразделение')),
                ('comment', models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Простои 5 линии',
            },
        ),
    ]
