# Generated by Django 4.1.6 on 2023-04-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0011_speed2_table2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table2',
            options={'verbose_name_plural': 'Простои 2 линии'},
        ),
    ]
