# Generated by Django 4.1.6 on 2023-04-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0014_productionoutput5'),
    ]

    operations = [
        migrations.CreateModel(
            name='NapAcratofori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('acr62_temp', models.IntegerField(verbose_name='Температура 62')),
                ('acr62_press', models.IntegerField(verbose_name='Давление 62')),
                ('acr62_volume', models.IntegerField(verbose_name='Обьем 62')),
                ('acr63_temp', models.IntegerField(verbose_name='Температура 63')),
                ('acr63_press', models.IntegerField(verbose_name='Давление 63')),
                ('acr63_volume', models.IntegerField(verbose_name='Обьем 63')),
                ('acr64_temp', models.IntegerField(verbose_name='Температура 64')),
                ('acr64_press', models.IntegerField(verbose_name='Давление 64')),
                ('acr64_volume', models.IntegerField(verbose_name='Обьем 64')),
                ('acr65_temp', models.IntegerField(verbose_name='Температура 65')),
                ('acr65_press', models.IntegerField(verbose_name='Давление 65')),
                ('acr65_volume', models.IntegerField(verbose_name='Обьем 65')),
                ('acr66_temp', models.IntegerField(verbose_name='Температура 66')),
                ('acr66_press', models.IntegerField(verbose_name='Давление 66')),
                ('acr66_volume', models.IntegerField(verbose_name='Обьем 66')),
                ('acr67_temp', models.IntegerField(verbose_name='Температура 67')),
                ('acr67_press', models.IntegerField(verbose_name='Давление 67')),
                ('acr67_volume', models.IntegerField(verbose_name='Обьем 67')),
                ('acr68_temp', models.IntegerField(verbose_name='Температура 68')),
                ('acr68_press', models.IntegerField(verbose_name='Давление 68')),
                ('acr68_volume', models.IntegerField(verbose_name='Обьем 68')),
                ('acr69_temp', models.IntegerField(verbose_name='Температура 69')),
                ('acr69_press', models.IntegerField(verbose_name='Давление 69')),
                ('acr69_volume', models.IntegerField(verbose_name='Обьем 69')),
                ('acr70_temp', models.IntegerField(verbose_name='Температура 70')),
                ('acr70_press', models.IntegerField(verbose_name='Давление 70')),
                ('acr70_volume', models.IntegerField(verbose_name='Обьем 70')),
                ('acr82_temp1', models.IntegerField(verbose_name='Температура 82 верх')),
                ('acr82_temp2', models.IntegerField(verbose_name='Температура 82 низ')),
                ('acr82_press', models.IntegerField(verbose_name='Давление 82')),
                ('acr82_volume', models.IntegerField(verbose_name='Обьем 82')),
                ('acr83_temp1', models.IntegerField(verbose_name='Температура 83 верх')),
                ('acr83_temp2', models.IntegerField(verbose_name='Температура 83 низ')),
                ('acr83_press', models.IntegerField(verbose_name='Давление 83')),
                ('acr83_volume', models.IntegerField(verbose_name='Обьем 83')),
            ],
        ),
    ]
