# Generated by Django 4.1.6 on 2023-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0015_napacratofori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='napacratofori',
            options={'verbose_name_plural': 'Напорные акратофоры'},
        ),
        migrations.AddField(
            model_name='bottling_plan',
            name='GIUDLine',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Линия GIUDLine'),
        ),
        migrations.AddField(
            model_name='bottling_plan',
            name='GUIDDocument',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='GUIDDocument'),
        ),
        migrations.AddField(
            model_name='bottling_plan',
            name='GUIDNomenсlature',
            field=models.CharField(blank=True, default=' ', max_length=32, null=True, verbose_name='GUIDNomenсlature'),
        ),
    ]
