# Generated by Django 4.1.6 on 2023-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0018_nomenclature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUID', models.CharField(max_length=32, verbose_name='GUID')),
                ('Line', models.CharField(max_length=50, verbose_name='Название линии')),
                ('Podrazdelenie', models.CharField(max_length=32, verbose_name='Подразделение')),
                ('PodrazdeleniePloshadka', models.CharField(max_length=32, verbose_name='ПодразделениеПлощадка')),
                ('NomerLine', models.IntegerField(verbose_name='Номер линии')),
            ],
            options={
                'verbose_name_plural': 'Линии',
            },
        ),
        migrations.AlterField(
            model_name='prichina',
            name='key',
            field=models.CharField(blank=True, default='Не определено', max_length=50, null=True, verbose_name='Подразделение'),
        ),
    ]
