# Generated by Django 4.1.6 on 2023-04-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0019_line_alter_prichina_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottling_plan',
            name='BottlingLine',
        ),
    ]
