# Generated by Django 4.1.6 on 2023-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0020_remove_bottling_plan_bottlingline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottling_plan',
            name='BottlingLine',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Линия розлива'),
        ),
    ]
