# Generated by Django 4.1.6 on 2023-04-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0021_bottling_plan_bottlingline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottling_plan',
            name='BottlingLine',
        ),
    ]
