# Generated by Django 4.1.6 on 2023-04-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0022_remove_bottling_plan_bottlingline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prichina',
            old_name='key',
            new_name='Podrazdelenie',
        ),
    ]
