# Generated by Django 4.1.6 on 2023-04-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0023_rename_key_prichina_podrazdelenie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prichina',
            old_name='Podrazdelenie',
            new_name='key',
        ),
    ]
