# Generated by Django 4.1.6 on 2023-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0027_alter_napacratofori_acr62_press_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='napacratofori',
            name='acr69_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Обьем 69'),
        ),
    ]
