# Generated by Django 4.1.6 on 2023-04-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0030_remove_bottling_plan_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottling_plan',
            name='Nomenclature',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Номенклатура'),
        ),
    ]
