# Generated by Django 4.1.6 on 2023-04-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prostoy', '0031_bottling_plan_nomenclature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottling_plan',
            name='Nomenclature',
        ),
    ]
